import './global.css';
export const metadata = {
  title: 'Welcome to application',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
